# Generated by Django 2.2.5 on 2019-10-02 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(choices=[(1, 'Хэчбек'), (2, 'Седан'), (3, 'Внедорожник'), (4, 'Универсал')], max_length=60),
        ),
    ]
